"use client";

import Link from "next/link";
import { ArrowLeft } from "lucide-react";

import AnalyticsHeader from "@/components/admin/analytics/AnalyticsHeader";
import useStatisticsYear from "@/customHooks/useStatisticsYear";
import useOrganizationOrdersAnalytics from "@/customHooks/useOrganizationOrdersAnalytics";

import OrdersStatistics from "@/components/admin/analytics/orders/OrdersStatistics";
import { OrdersChartMonthly } from "@/components/admin/analytics/orders/OrdersChartAnalytics";

import OrdersAnalyticsSkeleton from "@/components/skeleton/OrdersAnalyticsSkeleton";

import OrganizationDetailsError from "@/components/admin/organizationDetails/OrganizationDetailsError";

type Props = {
  id: string;
};

export default function OrganizationOrdersAnalytics({ id }: Props) {
  const { currentYear, handleYearChange, years } = useStatisticsYear();

  const { statistics, monthly, isLoading, isError, error, refetch } =
    useOrganizationOrdersAnalytics({
      id,
      year: currentYear,
    });

  if (isLoading) {
    return <OrdersAnalyticsSkeleton />;
  }

  if (isError) {
    return (
      <OrganizationDetailsError
        message={
          error?.message || "Error loading organization orders analytics."
        }
        onRetry={refetch}
      />
    );
  }

  if (!statistics) return null;

  return (
    <div className="space-y-6">
      <Link
        href={`/admin/organizations/${id}`}
        className="inline-flex items-center gap-2 text-sm font-medium text-muted-foreground transition-colors hover:text-foreground">
        <ArrowLeft className="h-4 w-4" />

        Back to organization
      </Link>

      <AnalyticsHeader
        year={currentYear}
        onYearChange={handleYearChange}
        years={years}
        header="Orders Analytics"
        title="Order activity and revenue generated by this organization over time."
      />

      <OrdersStatistics
        totalOrders={statistics.totalOrders}
        newOrders={statistics.newOrders}
        totalRevenue={statistics.totalRevenue}
        yearlyRevenue={statistics.yearlyRevenue}
        scope="organization"
      />

      <OrdersChartMonthly chartData={monthly} year={currentYear} />
    </div>
  );
}
