"use client";

import Link from "next/link";
import { ArrowLeft } from "lucide-react";

import AnalyticsHeader from "@/components/admin/analytics/AnalyticsHeader";
import useStatisticsYear from "@/customHooks/useStatisticsYear";
import useMyOrganizationOrdersAnalytics from "@/customHooks/useMyOrganizationOrdersAnalytics";

import OrdersStatistics from "@/components/admin/analytics/orders/OrdersStatistics";
import { OrdersChartMonthly } from "@/components/admin/analytics/orders/OrdersChartAnalytics";

import OrdersAnalyticsSkeleton from "@/components/skeleton/OrdersAnalyticsSkeleton";

import AnalyticsError from "./AnalyticsError";

export default function OrganizationOrdersAnalytics() {
  const { currentYear, handleYearChange, years } = useStatisticsYear();

  const { statistics, monthly, isLoading, isError, error, refetch } =
    useMyOrganizationOrdersAnalytics({ year: currentYear });

  if (isLoading) {
    return <OrdersAnalyticsSkeleton />;
  }

  if (isError) {
    return (
      <AnalyticsError
        message={
          error?.message || "Error loading your organization orders analytics."
        }
        onRetry={refetch}
      />
    );
  }

  if (!statistics) return null;

  return (
    <div className="space-y-6">
      <Link
        href="/instructor/organization-orders"
        className="inline-flex items-center gap-2 text-sm font-medium text-muted-foreground transition-colors hover:text-foreground">
        <ArrowLeft className="h-4 w-4" />

        Back to my orders
      </Link>

      <AnalyticsHeader
        year={currentYear}
        onYearChange={handleYearChange}
        years={years}
        header="Orders Analytics"
        title="Order activity and revenue generated by your organization over time."
      />

      <OrdersStatistics
        totalOrders={statistics.totalOrders}
        newOrders={statistics.newOrders}
        totalRevenue={statistics.totalRevenue}
        yearlyRevenue={statistics.yearlyRevenue}
        scope="organization"
      />

      <OrdersChartMonthly chartData={monthly} year={currentYear} />
    </div>
  );
}
