// Makes certificates appear on the instructor dashboard without touching the
// backend logic:
//   * for every approved organization, two of its courses are chosen
//   * if a chosen course has no buyer yet, one real student is enrolled
//     (order + user.courses + progress), exactly like a purchase would
//   * one real student who purchased each course is completed (progress = 100%)
//   * a certificate is generated through the real backend service
//     (generateCertificateService), so certificateId, learningHours and the
//     student/course snapshots are exactly what the app produces
//
// The instructor certificates page only lists certificates whose organization
// matches the logged in instructor, so every certificate generated here shows
// up only on that organization's dashboard.
//
// Run: npm run seed:certificates                      (dry run)
//      npm run seed:certificates -- --yes             (write)
//      npm run seed:certificates -- --yes --reset     (rebuild from scratch)
import "dotenv/config";
import mongoose, { Types } from "mongoose";

import UserModel from "../models/user.model";
import OrganizationModel from "../models/organization.model";
import CourseModel from "../models/course.model";
import OrderModel from "../models/order.model";
import CourseProgressModel from "../models/courseProgress.model";
import CertificateModel from "../models/certificate.model";
import { generateCertificateService } from "../services/certificate.service";
import redis from "../utils/redis";

const CERT_MARKER = "seed:certificates";

const flag = (name: string) => process.argv.includes(`--${name}`);
const arg = (name: string, fallback = "") => {
  const hit = process.argv.find((item) => item.startsWith(`--${name}=`));

  return hit ? hit.split("=").slice(1).join("=") : fallback;
};

const CONFIRMED = flag("yes") || arg("confirm", "") === "yes";
const RESET = flag("reset");

const PER_ORG = Math.max(
  1,
  Math.min(Number(arg("per-org", "2")) || 2, 5),
);

const run = async () => {
  await mongoose.connect(process.env.DB_URL as string);

  const orgs = await OrganizationModel.find({
    instructor: {
      $in: (
        await UserModel.find({ role: "instructor", email: /^inst\./ }).select("_id").lean()
      ).map((user: any) => user._id),
    },
  })
    .select("_id name")
    .lean();

  const courses = await CourseModel.find()
    .select("name organization price courseData")
    .lean();

  const students = await UserModel.find({ role: "user" }).select("_id").lean();
  const allOrders = await OrderModel.find().select("user course").lean();

  console.log("");
  console.log("=== certificate plan ===");
  console.log(`  organizations : ${orgs.length}`);
  console.log(`  completions   : ${PER_ORG} course(s) completed per organization`);
  console.log(`  certificates  : ${orgs.length * PER_ORG}`);
  console.log("  each certificate is generated by the real backend service");

  if (!CONFIRMED) {
    console.log("\n  DRY RUN, nothing was written. re-run with --yes.\n");
    await mongoose.disconnect();
    await redis.quit();
    process.exit(0);
  }

  const buyersPerCourse = new Map<string, string[]>();
  const purchasesPerStudent = new Map<string, number>();
  for (const order of allOrders) {
    const key = String(order.course);
    if (!buyersPerCourse.has(key)) buyersPerCourse.set(key, []);
    buyersPerCourse.get(key)!.push(String(order.user));

    const who = String(order.user);
    purchasesPerStudent.set(who, (purchasesPerStudent.get(who) || 0) + 1);
  }

  if (RESET) {
    console.log("\n--- reset ---");
    // remove the orders/enrollments this script adds, so a reset always
    // reproduces the exact same state
    const extraOrders = await OrderModel.find({
      "paymentInfo.metadata.seed": CERT_MARKER,
    })
      .select("user course")
      .lean();

    const extraPairs = extraOrders.map((order: any) => ({
      user: String(order.user),
      course: String(order.course),
    }));
    const extraCourseIds = [...new Set(extraPairs.map((pair) => pair.course))];

    await OrderModel.deleteMany({ "paymentInfo.metadata.seed": CERT_MARKER });
    await CourseProgressModel.deleteMany({
      $or: extraPairs.map((pair) => ({ user: pair.user, course: pair.course })),
    });
    await UserModel.updateMany({}, { $pull: { courses: { $in: extraCourseIds } } });

    // recompute the purchased counter from the remaining orders
    const remaining = await OrderModel.find().select("course").lean();
    const counts = new Map<string, number>();
    for (const order of remaining) {
      counts.set(String(order.course), (counts.get(String(order.course)) || 0) + 1);
    }
    const purchasedUpdates = extraCourseIds.map((courseId) => ({
      updateOne: {
        filter: { _id: courseId },
        update: { $set: { purchased: counts.get(courseId) || 0 } },
      },
    }));
    if (purchasedUpdates.length) {
      await CourseModel.bulkWrite(purchasedUpdates, { ordered: false });
    }

    console.log(
      `  ${extraOrders.length} script enrollments removed, ${await CertificateModel.countDocuments()} certificates dropped`,
    );
    await CertificateModel.deleteMany({});
  }

  console.log("\n--- completing progress and generating certificates ---");
  let completed = 0;
  let certificates = 0;
  const cacheKeys = new Set<string>();

  for (const org of orgs) {
    const orgCourses = courses
      .filter((course: any) => String(course.organization) === String(org._id))
      .map((course: any) => ({
        _id: course._id,
        name: course.name,
        price: course.price || 0,
        lectures: (course.courseData || []).map((lecture: any) => lecture._id),
        buyers: buyersPerCourse.get(String(course._id)) || [],
      }))
      .sort(
        (a, b) =>
          b.buyers.length - a.buyers.length || a.name.localeCompare(b.name),
      );

    const takenInOrg = new Set<string>();

    for (const course of orgCourses) {
      if (takenInOrg.size >= PER_ORG) break;
      if (course.lectures.length === 0) continue;

      const progressRows = await CourseProgressModel.find({
        course: course._id,
        user: { $in: course.buyers },
      })
        .select("user completedLectures")
        .lean();

      const sorted = [...progressRows].sort(
        (a: any, b: any) => a.completedLectures.length - b.completedLectures.length,
      );
      const buyer = sorted.length ? String(sorted[0].user) : course.buyers[0];

      if (buyer) {
        takenInOrg.add(String(course._id));
        await markComplete(buyer, course);
        await issue(buyer, course, org.name);
        completed += 1;
        certificates += 1;
        continue;
      }

      // no buyer yet: enroll a real student into this course first
      const freeStudent = pickFreeStudent(students, purchasesPerStudent);
      if (!freeStudent) continue;

      await OrderModel.create({
        user: new Types.ObjectId(freeStudent),
        course: new Types.ObjectId(String(course._id)),
        organization: new Types.ObjectId(String(org._id)),
        price: course.price,
        paymentInfo: {
          id: `pi_cert_${String(freeStudent).slice(-8)}_${String(course._id).slice(-8)}`,
          amount: Math.round(course.price * 100),
          currency: "egp",
          status: "succeeded",
          payment_method: "card",
          created: Math.floor(Date.now() / 1000),
          metadata: { seed: CERT_MARKER, userId: freeStudent, courseId: String(course._id) },
        },
      });

      await UserModel.updateOne(
        { _id: freeStudent },
        { $addToSet: { courses: course._id } },
      );
      await markComplete(freeStudent, course);
      purchasesPerStudent.set(freeStudent, (purchasesPerStudent.get(freeStudent) || 0) + 1);

      takenInOrg.add(String(course._id));
      await issue(freeStudent, course, org.name);
      completed += 1;
      certificates += 1;

      // keep the counter and the real relations consistent
      const count = await OrderModel.countDocuments({ course: course._id });
      await CourseModel.updateOne(
        { _id: course._id },
        { $set: { purchased: count } },
      );
    }
  }

  console.log(
    `\n  ${completed} course progresses completed, ${certificates} certificates generated`,
  );

  // any student changed by this script gets its redis cache cleared
  for (const order of allOrders) cacheKeys.add(String(order.user));
  const certUsers = await CertificateModel.find().select("user").lean();
  for (const certificate of certUsers) cacheKeys.add(String(certificate.user));

  for (let i = 0; i < cacheKeys.size; i += 200) {
    await redis.del(...[...cacheKeys].slice(i, i + 200));
  }
  console.log(`  ${cacheKeys.size} redis cache keys cleared`);

  // verify how the instructor dashboard will read the data
  console.log("\n=== verification ===");
  console.log(`  certificates total: ${await CertificateModel.countDocuments()}`);
  const perOrg = await CertificateModel.aggregate([
    { $group: { _id: "$organization", count: { $sum: 1 } } },
    { $sort: { count: -1 } },
  ]);
  console.log(
    `  per organization: ${[...perOrg.map((x: any) => x.count)].join(", ")}`,
  );

  const courseSizes = new Map(
    courses.map((course: any) => [String(course._id), (course.courseData || []).length]),
  );
  const certRows = await CertificateModel.find().select("user course").lean();
  const progressRows = await CourseProgressModel.find()
    .select("user course completedLectures")
    .lean();
  let at100 = 0;
  for (const certificate of certRows) {
    const row: any = progressRows.find(
      (p: any) =>
        String(p.user) === String(certificate.user) &&
        String(p.course) === String(certificate.course),
    );
    const size = courseSizes.get(String(certificate.course)) || 0;
    if (row && size && row.completedLectures.length >= size) at100 += 1;
  }
  console.log(`  certificates whose progress is truly 100%: ${at100}/${certRows.length}`);
  console.log("\n  done\n");

  await mongoose.disconnect();
  await redis.quit();
  process.exit(0);
};

const markComplete = async (userId: string, course: any) => {
  return CourseProgressModel.updateOne(
    { user: userId, course: course._id },
    {
      $set: {
        currentLecture: course.lectures[course.lectures.length - 1],
        completedLectures: course.lectures,
        lastAccessedAt: new Date(),
      },
    },
    { upsert: true },
  );
};

const issue = async (userId: string, course: any, orgName: string) => {
  const certificate = await generateCertificateService(userId, String(course._id));
  const user = await UserModel.findById(userId).select("name").lean();

  console.log(
    `  ${orgName.padEnd(26)} ${String(course.name || "").slice(0, 34).padEnd(36)} ${(user as any)?.name || userId}  -> ${certificate.certificateId}`,
  );
};

const pickFreeStudent = (
  students: any[],
  purchasesPerStudent: Map<string, number>,
) =>
  [...students]
    .sort((a, b) => {
      const diff =
        (purchasesPerStudent.get(String(a._id)) || 0) -
        (purchasesPerStudent.get(String(b._id)) || 0);
      return diff !== 0 ? diff : String(a._id).localeCompare(String(b._id));
    })
    .map((student: any) => String(student._id))[0];

run().catch(async (error) => {
  console.error("\nFAILED:", error && error.message);
  process.exitCode = 1;

  try {
    await mongoose.disconnect();
    await redis.quit();
  } catch {
    // ignore shutdown errors
  }

  process.exit(1);
});